name: 'CI'

on:
  push:
    branches:
      - main
jobs:
  build:
    name: 'Build and Push'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test

      - name: Run E2E Tests
        run: pnpm run test:e2e
